Repository kayla-himmel/solitaire, pull requests merged in 2023-02, with the labels that each got.

#7 Shuffle functionality
  solitaire-game/src/App.tsx
  solitaire-game/src/components/DeckObject.tsx
  solitaire-game/src/components/cards/Card.interfaces.tsx
  solitaire-game/src/components/cards/Card.tsx
Labels: ready for review

#8 PR Template
  .github/pull_request_template.md
Labels: changes requested

#10 Setup: Add testing, sass, and prettier configs
  solitaire-game/.eslintrc.js
  solitaire-game/.prettierignore
  solitaire-game/.prettierrc
  solitaire-game/.testcaferc.json
  solitaire-game/.vscode/settings.json
  solitaire-game/README.md
  solitaire-game/jest.config.js
  solitaire-game/package-lock.json
  solitaire-game/package.json
  solitaire-game/src/App.css
  solitaire-game/src/App.test.tsx
  solitaire-game/src/App.tsx
  solitaire-game/src/components/example/Example.scss
  solitaire-game/src/components/example/Example.tsx
  solitaire-game/src/index.css
  solitaire-game/src/index.scss
  solitaire-game/src/index.tsx
  solitaire-game/src/styles.scss
  solitaire-game/tsconfig.json
Labels: Comments present, ready to merge
